services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ./config/sonarr-config:/config
      - ${ROOT_DIR_2}/data/tv:/data/tv
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ./config/radarr-config:/config
      - ${ROOT_DIR}/data/movies:/data/movies
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=13013
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ./config/bazarr-config:/config
      - ${ROOT_DIR}/data/movies/media:/data/movies/media
      - ${ROOT_DIR_2}/data/tv/media:/data/tv/media
    ports:
      - 6767:6767
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ./config/prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${M_UID}
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_URL}
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - ./config/jellyfin-config:/config
      - ${ROOT_DIR}/data/movies/media:/data/movies/media
      - ${ROOT_DIR_2}/data/tv/media:/data/tv/media
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./config/qbittorrent-config:/config
      - ${ROOT_DIR}/data/movies/torrents:/data/movies/torrents
      - ${ROOT_DIR_2}/data/tv/torrents:/data/tv/torrents
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=13011
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ./config/sabnzbd-config:/config
      - ${ROOT_DIR}/data/movies/usenet:/data/movies/usenet
      - ${ROOT_DIR_2}/data/tv/usenet:/data/tv/usenet
    ports:
      - "8081:8080"
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE}
    ports:
      - 8191:8191
    restart: unless-stopped

  openai-whisper-asr-webservice:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: openai-whisper-asr-webservice
    environment:
      - ASR_ENGINE=faster_whisper
      - ASR_MODEL=base
    ports:
      - 9000:9000
    restart: unless-stopped

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    user: 1000:13000
    volumes:
      - ./config/recyclarr-config:/config
    environment:
      - TZ=${TIMEZONE}

  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=${M_UID}
      - PGID=13000
      - TZ=${TIMEZONE}
      - SUBFOLDER=/
    volumes:
      - ./config/emulatorjs-config:/config
      - ./data/emulatorjs-data:/data
    ports:
      - 3000:3000
      - 80:80
      - 4001:4001
    restart: unless-stopped
